#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
    "${NEXTCLOUD_PATH}" \
    /config/crontabs

# install app
if [ ! -e "${NEXTCLOUD_PATH}/index.php" ]; then
    tar xf /app/nextcloud.tar.bz2 -C \
        "${NEXTCLOUD_PATH}" --strip-components=1
    chown abc:abc -R \
        "${NEXTCLOUD_PATH}"
    chmod +x "${NEXTCLOUD_PATH}/occ"
fi

# copy nginx defaults if needed
[[ ! -f /config/nginx/server-confs/ssl.conf ]] && \
    cp /defaults/nginx/server-confs/ssl.conf.sample /config/nginx/server-confs/ssl.conf

# set cronjob
[[ ! -f /config/crontabs/root ]] && \
    cp /defaults/root /config/crontabs/root
cp /config/crontabs/root /etc/crontabs/root
